youtube_video_statistics:
  outputs:
    dev:
      database: YOUTUBE_VIDEO_STATISTICS_DEV
      schema: DBT
      role: ACCOUNTADMIN
      type: snowflake
      warehouse: COMPUTE_WH
      account: 'not needed'
      user: 'not needed'
    prod:
      database: YOUTUBE_VIDEO_STATISTICS
      schema: DBT
      role: ACCOUNTADMIN
      type: snowflake
      warehouse: COMPUTE_WH
      account: 'not needed'
      user: 'not needed'
  target: dev