version: 2

models:
  - name: videos_r
    description: "Transformed videos"
    columns:
      - name: video_id
      - name: trending_date
      - name: title
      - name: channel_title
      - name: category_id
      - name: publish_time
      - name: tags
      - name: views
      - name: likes
      - name: dislikes
      - name: comment_count
      - name: thumbnail_link
      - name: comments_disabled
      - name: ratings_disabled
      - name: video_error_or_removed
      - name: description
      - name: file_names
      - name: etl_inserted_timestamp
